# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='Hello', max_length=255),
        ),
    ]
